name: CI

on: 
 push:
   branches: 
     - master
       - release/*
  
 on:
    pull_requst:
     branches:
     - master
       
    on:
      schedule:
       - cron: "0 2 * * 1-5"
  

    jobs:
      my_job:
      name: deploy to staging
      runs-on: ubuntu-latest
      
          -name:Setup Node
              uses:actions/setup-node@v1
              with:
                node-version: '10.x'
            
      - name: Install Dependencies
        run: npm install
        
       
 jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
     
     build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
 
     build:
     
     
     
     runs-on: ubuntu-latest
     
     
     steps:
     - uses: actions/
       
